export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_EXPENSES = 'GET_EXPENSES';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const EXPENSES_LOADING = 'EXPENSES_LOADING';
export const EXPENSES_NOT_FOUND = 'EXPENSES_NOT_FOUND';
export const CLEAR_CURRENT_EXPENSES = 'CLEAR_CURRENT_EXPENSES';
